FROM centos:7
MAINTAINER dangkiena3@gmail.com



RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf

RUN yum -y update && \ 
    yum -y install make automake gcc gcc-c++ GeoIP GeoIP-devel \
    yum -y install ruby rubygems ruby-devel && \
    gem install fpm
